#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the boot_user.mk file instead.
#

# Constants automatically defined by the selected modules
boot_DEBUG = 1

# Our target application
TRG += boot

boot_PREFIX = "arm-none-eabi-"

boot_SUFFIX = ""

boot_SRC_PATH = boot

boot_HW_PATH = .

# Files automatically generated by the wizard. DO NOT EDIT, USE boot_USER_CSRC INSTEAD!
boot_WIZARD_CSRC = \
	bertos/cpu/arm/drv/timer_arm.c \
	bertos/fs/fat.c \
	bertos/io/kfile.c \
	bertos/cpu/arm/drv/sysirq_at91.c \
	bertos/mware/formatwr.c \
	bertos/cpu/arm/drv/timer_at91.c \
	bertos/drv/timer.c \
	bertos/fs/fatfs/ff.c \
	bertos/mware/event.c \
	bertos/mware/hex.c \
	bertos/drv/sd.c \
	bertos/io/kfile_block.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE boot_USER_PCSRC INSTEAD!
boot_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE boot_USER_CPPASRC INSTEAD!
boot_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE boot_USER_CXXSRC INSTEAD!
boot_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE boot_USER_ASRC INSTEAD!
boot_WIZARD_ASRC = \
	 \
	#

boot_CPPFLAGS = -D'CPU_FREQ=(48000000L)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(boot_HW_PATH) -I$(boot_SRC_PATH) $(boot_CPU_CPPFLAGS) $(boot_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_LDFLAGS = $(boot_CPU_LDFLAGS) $(boot_WIZARD_LDFLAGS) $(boot_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_CPPAFLAGS = $(boot_CPU_CPPAFLAGS) $(boot_WIZARD_CPPAFLAGS) $(boot_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_CSRC = $(boot_CPU_CSRC) $(boot_WIZARD_CSRC) $(boot_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_PCSRC = $(boot_CPU_PCSRC) $(boot_WIZARD_PCSRC) $(boot_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_CPPASRC = $(boot_CPU_CPPASRC) $(boot_WIZARD_CPPASRC) $(boot_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_CXXSRC = $(boot_CPU_CXXSRC) $(boot_WIZARD_CXXSRC) $(boot_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_ASRC = $(boot_CPU_ASRC) $(boot_WIZARD_ASRC) $(boot_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_CPU_CPPASRC = bertos/cpu/arm/hw/crt_arm7tdmi.S bertos/cpu/arm/hw/vectors_at91.S
boot_CPU_CPPAFLAGS = -g -gdwarf-2
boot_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -fverbose-asm -Ibertos/cpu/arm/ -D__ARM_AT91SAM7S256__
boot_CPU_CSRC = bertos/cpu/arm/hw/init_at91.c
boot_PROGRAMMER_CPU = at91sam7-0.4
boot_CPU_LDFLAGS = -nostartfiles -Wl,--no-warn-mismatch -T bertos/cpu/arm/scripts/at91sam7_256_rom.ld
boot_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
boot_CPU = arm7tdmi
boot_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
boot_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
boot_FLASH_SCRIPT = bertos/prg_scripts/arm/flash.sh

include $(boot_SRC_PATH)/boot_user.mk
