#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the aprs_decoder_user.mk file instead.
#

# Constants automatically defined by the selected modules
aprs_decoder_DEBUG = 1

# Our target application
TRG += aprs_decoder

aprs_decoder_PREFIX = ""

aprs_decoder_SUFFIX = ""

aprs_decoder_SRC_PATH = aprs_decoder

aprs_decoder_HW_PATH = aprs_decoder

# Files automatically generated by the wizard. DO NOT EDIT, USE aprs_decoder_USER_CSRC INSTEAD!
aprs_decoder_WIZARD_CSRC = \
	bertos/mware/event.c \
	bertos/algo/crc_ccitt.c \
	bertos/net/afsk.c \
	bertos/net/ax25.c \
	bertos/io/kfile.c \
	bertos/mware/formatwr.c \
	bertos/drv/timer.c \
	bertos/mware/hex.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE aprs_decoder_USER_PCSRC INSTEAD!
aprs_decoder_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE aprs_decoder_USER_CPPASRC INSTEAD!
aprs_decoder_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE aprs_decoder_USER_CXXSRC INSTEAD!
aprs_decoder_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE aprs_decoder_USER_ASRC INSTEAD!
aprs_decoder_WIZARD_ASRC = \
	 \
	#

aprs_decoder_CPPFLAGS = -D'CPU_FREQ=(48054857UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(aprs_decoder_HW_PATH) -I$(aprs_decoder_SRC_PATH) $(aprs_decoder_CPU_CPPFLAGS) $(aprs_decoder_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_decoder_LDFLAGS = $(aprs_decoder_CPU_LDFLAGS) $(aprs_decoder_WIZARD_LDFLAGS) $(aprs_decoder_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_decoder_CPPAFLAGS = $(aprs_decoder_CPU_CPPAFLAGS) $(aprs_decoder_WIZARD_CPPAFLAGS) $(aprs_decoder_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_decoder_CSRC = $(aprs_decoder_CPU_CSRC) $(aprs_decoder_WIZARD_CSRC) $(aprs_decoder_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_decoder_PCSRC = $(aprs_decoder_CPU_PCSRC) $(aprs_decoder_WIZARD_PCSRC) $(aprs_decoder_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_decoder_CPPASRC = $(aprs_decoder_CPU_CPPASRC) $(aprs_decoder_WIZARD_CPPASRC) $(aprs_decoder_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_decoder_CXXSRC = $(aprs_decoder_CPU_CXXSRC) $(aprs_decoder_WIZARD_CXXSRC) $(aprs_decoder_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_decoder_ASRC = $(aprs_decoder_CPU_ASRC) $(aprs_decoder_WIZARD_ASRC) $(aprs_decoder_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
aprs_decoder_CPU_CPPAFLAGS = -g -gdwarf-2
aprs_decoder_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -fverbose-asm
aprs_decoder_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
aprs_decoder_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
aprs_decoder_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
aprs_decoder_FLASH_SCRIPT = bertos/prg_scripts/arm/flash.sh

include $(aprs_decoder_SRC_PATH)/aprs_decoder_user.mk
