// Emtpy main.c file generated by the wizard

#include "hw/hw_pin.h"
#include <cpu/irq.h>
#include <cfg/debug.h>

#include <kern/proc.h>
#include <drv/timer.h>
#include <drv/kbd.h>


static void init(void)
{
	IRQ_ENABLE;
	kdbg_init();
	timer_init();
	kbd_init();
	proc_init();

	PIOA_CODR = LEDR | LEDG | BUZZER_BIT | CUTOFF_PIN | LAND_PIN;
	PIOA_OER = LEDR | LEDG | BUZZER_BIT | CUTOFF_PIN | LAND_PIN;
}


static void loop_pin(void)
{
	int pins[] = {LEDR , LEDG , BUZZER_BIT , LAND_PIN, LAND_PIN };
	for (unsigned i = 0; i < countof(pins); i++)
	{
		PIOA_SODR = pins[i];
		timer_delay(1000);
		PIOA_CODR = pins[i];
	}
}

static void pushbutton(void)
{
	if (kbd_peek() & K_START)
	{
		PIOA_SODR = LEDR | LEDG | CUTOFF_PIN | LAND_PIN;
		timer_delay(5000);
	}

	PIOA_CODR = LEDR | LEDG | BUZZER_BIT | CUTOFF_PIN | LAND_PIN;
}

int main(void)
{
	init();

	while (1)
	{
		//loop_pin();
		pushbutton();
	}

	return 0;
}

