#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the bsm-2_user.mk file instead.
#

# Constants automatically defined by the selected modules
bsm-2_DEBUG = 1

# Our target application
TRG += bsm-2

bsm-2_PREFIX = "arm-none-eabi-"

bsm-2_SUFFIX = ""

bsm-2_SRC_PATH = bsm-2

bsm-2_HW_PATH = .

# Files automatically generated by the wizard. DO NOT EDIT, USE bsm-2_USER_CSRC INSTEAD!
bsm-2_WIZARD_CSRC = \
	bertos/net/afsk.c \
	bertos/mware/formatwr.c \
	bertos/cpu/arm/drv/timer_at91.c \
	bertos/net/nmea.c \
	bertos/mware/sprintf.c \
	bertos/io/kfile.c \
	bertos/cpu/arm/drv/ser_arm.c \
	bertos/algo/crc_ccitt.c \
	bertos/cpu/arm/drv/ser_at91.c \
	bertos/struct/heap.c \
	bertos/fs/fatfs/ff.c \
	bertos/drv/ser.c \
	bertos/drv/buzzer.c \
	bertos/mware/hex.c \
	bertos/net/nmeap/src/nmeap01.c \
	bertos/drv/timer.c \
	bertos/struct/kfile_fifo.c \
	bertos/kern/proc.c \
	bertos/drv/sd.c \
	bertos/mware/event.c \
	bertos/cpu/arm/drv/sysirq_at91.c \
	bertos/net/ax25.c \
	bertos/kern/monitor.c \
	bertos/cpu/arm/drv/timer_arm.c \
	bertos/fs/fat.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE bsm-2_USER_PCSRC INSTEAD!
bsm-2_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE bsm-2_USER_CPPASRC INSTEAD!
bsm-2_WIZARD_CPPASRC = \
	bertos/cpu/arm/hw/switch_ctx_arm.S \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE bsm-2_USER_CXXSRC INSTEAD!
bsm-2_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE bsm-2_USER_ASRC INSTEAD!
bsm-2_WIZARD_ASRC = \
	 \
	#

bsm-2_CPPFLAGS = -D'CPU_FREQ=(48054857L)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(bsm-2_HW_PATH) -I$(bsm-2_SRC_PATH) $(bsm-2_CPU_CPPFLAGS) $(bsm-2_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-2_LDFLAGS = $(bsm-2_CPU_LDFLAGS) $(bsm-2_WIZARD_LDFLAGS) $(bsm-2_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-2_CPPAFLAGS = $(bsm-2_CPU_CPPAFLAGS) $(bsm-2_WIZARD_CPPAFLAGS) $(bsm-2_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-2_CSRC = $(bsm-2_CPU_CSRC) $(bsm-2_WIZARD_CSRC) $(bsm-2_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-2_PCSRC = $(bsm-2_CPU_PCSRC) $(bsm-2_WIZARD_PCSRC) $(bsm-2_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-2_CPPASRC = $(bsm-2_CPU_CPPASRC) $(bsm-2_WIZARD_CPPASRC) $(bsm-2_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-2_CXXSRC = $(bsm-2_CPU_CXXSRC) $(bsm-2_WIZARD_CXXSRC) $(bsm-2_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-2_ASRC = $(bsm-2_CPU_ASRC) $(bsm-2_WIZARD_ASRC) $(bsm-2_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-2_CPU_CPPASRC = bertos/cpu/arm/hw/crt_arm7tdmi.S bertos/cpu/arm/hw/vectors_at91.S
bsm-2_CPU_CPPAFLAGS = -g -gdwarf-2
bsm-2_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -fverbose-asm -Ibertos/cpu/arm/ -D__ARM_AT91SAM7S256__
bsm-2_CPU_CSRC = bertos/cpu/arm/hw/init_at91.c
bsm-2_PROGRAMMER_CPU = at91sam7
bsm-2_CPU_LDFLAGS = -nostartfiles -Wl,--no-warn-mismatch -T bertos/cpu/arm/scripts/at91sam7_256_rom.ld
bsm-2_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
bsm-2_CPU = arm7tdmi
bsm-2_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
bsm-2_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
bsm-2_FLASH_SCRIPT = bertos/prg_scripts/arm/flash.sh

include $(bsm-2_SRC_PATH)/bsm-2_user.mk
