#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the bsm-radio_user.mk file instead.
#

# Constants automatically defined by the selected modules
bsm-radio_DEBUG = 1

# Our target application
TRG += bsm-radio

bsm-radio_PREFIX = "/usr/local/toolchain/arm/bin/arm-none-eabi-"

bsm-radio_SUFFIX = ""

bsm-radio_SRC_PATH = bsm-radio

bsm-radio_HW_PATH = bsm-radio

# Files automatically generated by the wizard. DO NOT EDIT, USE bsm-radio_USER_CSRC INSTEAD!
bsm-radio_WIZARD_CSRC = \
	bertos/cpu/cortex-m3/drv/timer_cm3.c \
	bertos/drv/spi_bitbang.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE bsm-radio_USER_PCSRC INSTEAD!
bsm-radio_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE bsm-radio_USER_CPPASRC INSTEAD!
bsm-radio_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE bsm-radio_USER_CXXSRC INSTEAD!
bsm-radio_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE bsm-radio_USER_ASRC INSTEAD!
bsm-radio_WIZARD_ASRC = \
	 \
	#

bsm-radio_CPPFLAGS = -D'CPU_FREQ=(24000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(bsm-radio_HW_PATH) -I$(bsm-radio_SRC_PATH) $(bsm-radio_CPU_CPPFLAGS) $(bsm-radio_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-radio_LDFLAGS = $(bsm-radio_CPU_LDFLAGS) $(bsm-radio_WIZARD_LDFLAGS) $(bsm-radio_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-radio_CPPAFLAGS = $(bsm-radio_CPU_CPPAFLAGS) $(bsm-radio_WIZARD_CPPAFLAGS) $(bsm-radio_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-radio_CSRC = $(bsm-radio_CPU_CSRC) $(bsm-radio_WIZARD_CSRC) $(bsm-radio_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-radio_PCSRC = $(bsm-radio_CPU_PCSRC) $(bsm-radio_WIZARD_PCSRC) $(bsm-radio_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-radio_CPPASRC = $(bsm-radio_CPU_CPPASRC) $(bsm-radio_WIZARD_CPPASRC) $(bsm-radio_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-radio_CXXSRC = $(bsm-radio_CPU_CXXSRC) $(bsm-radio_WIZARD_CXXSRC) $(bsm-radio_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-radio_ASRC = $(bsm-radio_CPU_ASRC) $(bsm-radio_WIZARD_ASRC) $(bsm-radio_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
bsm-radio_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S 
bsm-radio_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
bsm-radio_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32F100C4__
bsm-radio_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c 
bsm-radio_PROGRAMMER_CPU = stm32
bsm-radio_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -Wl,-dT bertos/cpu/cortex-m3/scripts/stm32f100c4_rom.ld
bsm-radio_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
bsm-radio_CPU = cortex-m3
bsm-radio_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
bsm-radio_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
bsm-radio_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32f100.sh

include $(bsm-radio_SRC_PATH)/bsm-radio_user.mk
