// Empty main.c file generated by the wizard
#include <cfg/debug.h>

#include <cpu/irq.h>

#include <drv/timer.h>

static void init(void)
{
	IRQ_ENABLE;
	kdbg_init();
	timer_init();
}

int main(void)
{
	init();
	while (1)
	{
		kputs("BSM Radio start!\n");
		timer_delay(500);
	}

	return 0;
}

